# @route = http://localhost:8080/products
@route = http://localhost:3001/api/v1/products

### GET ALL
GET {{route}} HTTP/1.1

### GET ALL WITH SORT BY NAME 
GET {{route}}?name=energetica&sortBy=price&sortType=desc HTTP/1.1

### POST GENERATE INVOICE PDF
POST {{route}}/generate-invoice HTTP/1.1

{
  '5': [
    {
      id: 5,
      name: 'energetica mr big',
      url_image: 'https://dojiw2m9tvv09.cloudfront.net/11132/productmisterbig3308256.jpg',
      price: 1490,
      discount: 20,
      category: 1
    }
  ],
}

### GET BY ID
GET {{route}}/99 HTTP/1.1